export const DATABASE_CONNECTION: string = 'DATABASE_CONNECTION';
export const TESTING_REPOSITORY: string = 'TESTING_REPOSITORY';
export const TESTING_INDICATOR_REPOSITORY: string = 'TESTING_INDICATOR_REPOSITORY';
export const INDICATOR_REPOSITORY: string = 'INDICATOR_REPOSITORY';
